"""Template Builder for dynamic markdown templates."""

import json
import logging
from typing import Dict, Any

from showup_core.api_client import generate_with_claude
from showup_core.model_config import get_model_provider
from showup_core.utils import load_prompt

logger = logging.getLogger(__name__)

async def generate_markdown_template(plan: Dict[str, Any], settings: Dict[str, Any]) -> str:
    """Generate a markdown template from a finalized content plan.

    Args:
        plan: The finalized content plan as a dictionary.
        settings: Configuration containing model_id, temperature, max_tokens and optional API keys.

    Returns:
        The markdown template string generated by the language model.
    """
    logger.info("Generating markdown template from plan")

    prompt_template = load_prompt("planning/generate_template_from_plan")
    if not prompt_template:
        logger.error("Template generation prompt not found")
        raise FileNotFoundError("generate_template_from_plan prompt missing")

    plan_str = json.dumps(plan, ensure_ascii=False)
    prompt = prompt_template.replace("{{final_plan}}", plan_str)

    model_id = settings.get("model_id", "claude-3-haiku-20240307")
    provider = get_model_provider(model_id)

    max_tokens = settings.get("max_tokens", 1000)
    temperature = settings.get("temperature", 0.3)

    if provider == "openai":
        import openai
        client = openai.OpenAI(api_key=settings.get("openai_api_key"))
        response = client.chat.completions.create(
            model=model_id,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=max_tokens,
            temperature=temperature,
        )
        return response.choices[0].message.content

    result = await generate_with_claude(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        model=model_id,
        task_type="template_generation",
    )
    return result
